name: Build Project

on: workflow_dispatch

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:

  copyTomlFile:
    needs: Deploy_WEBGL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.2
        env:
          key: master
          branches: webpage
          files: netlify.toml

  buildWebGL:
    name: Build for WebGL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
          
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
          
      - uses: game-ci/unity-builder@v2.0.4
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          
      - uses: actions/upload-artifact@v2
        with:
          name: build-WebGL
          path: build/WebGL
    

  Deploy_WEBGL:
      needs: buildWebGL
      name: Deploy to Pages
      runs-on: ubuntu-latest
      steps:
      
      - name: work around permission issue
        run: git config --global --add safe.directory /github/workspace
    
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1
        env:
          key: master
          branches: webpage
          files: netlify.toml
        
      - uses: actions/download-artifact@v2
        with:
          name: build-WebGL
          path: build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: webpage
          folder: build/WebGL
